  ner-service:
    build:
      context: ./ner-service
      dockerfile: Dockerfile
    container_name: ner_ner_service
    environment:
      - ENTITY_DICT_SERVICE_URL=http://entity-dictionary-service:8004
      - REDIS_URL=redis://redis:6379/2
    ports:
      - "8002:8002"
    depends_on:
      - redis
      - entity-dictionary-service
    volumes:
      - ./ner-service:/app
      - ./data:/app/data  # <-- ДОБАВИТЬ ЭТУ СТРОКУ!